name: Remove 'awaiting response' label

on:
  issue_comment:
    types: [created, edited]

jobs:
  remove-awaiting-response-label:
    runs-on: ubuntu-latest
    steps:
      - name: Remove 'awaiting response' label and maybe reopen
        if: contains(github.event.issue.labels.*.name, 'awaiting response')
        run: |
          gh issue edit $ISSUE --remove-label 'awaiting response'
          gh issue reopen $ISSUE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE: ${{ github.event.issue.html_url }}
