on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '51 3 * * Fri'

name: R-CMD-check

defaults:
  run:
    shell: Rscript {0}

jobs:
  R-CMD-check:
    name: ${{ matrix.os }}, py-${{ matrix.python }}, R-${{ matrix.r }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        include:

          ## the happy path - default everything
          - {os: 'ubuntu-latest' , python: '3.10', r: 'release'}
          - {os: 'windows-latest', python: '3.10', r: 'release'}
          - {os: 'macOS-latest'  , python: '3.10', r: 'release'}

          ## different python versions
          - {os: 'ubuntu-latest' , python: '3.11', r: 'release'}
          - {os: 'ubuntu-latest' , python: '3.9' , r: 'release'}
          # - {os: 'ubuntu-20.04'  , python: '3.8' , r: '3.6'} # default R in ubuntu-20.04 # install/pak failure?

          ## older R versions
          # to see the current oldrel-3 (4.0.5):
          # https://api.r-hub.io/rversions/resolve/oldrel/3
          - {os: 'ubuntu-latest' , python: '3.9', r: 'oldrel-1'}
          - {os: 'ubuntu-latest' , python: '3.9', r: 'oldrel-2'}
          - {os: 'ubuntu-latest' , python: '3.9', r: 'oldrel-3'}

          # these are allowed to fail
          # - {os: 'ubuntu-latest', tf: '2.14.0rc1', r: 'release'}
          # - {os: 'ubuntu-20.04', tf: 'default', r: 'devel'}
          # - {os: 'ubuntu-20.04', tf: 'nightly' , r: 'release'}

    runs-on: ${{ matrix.os }}
    # continue-on-error: ${{ matrix.tf == 'nightly' || contains(matrix.tf, 'rc') || matrix.r == 'devel' }}
    env:
      R_KEEP_PKG_SOURCE: yes
      # R_REMOTES_NO_ERRORS_FROM_WARNINGS: 'true'
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        id: setup-r
        with:
          r-version: ${{ matrix.r }}
          use-public-rspm: true
          Ncpus: '2L'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, local::.
          cache-version: 1
          upgrade: 'TRUE'

      - name: Install Keras
        run: keras3::install_keras(python_version = '${{ matrix.python }}')

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
