on:
  push:
    branches: master

name: Pkgdown

jobs:
  pkgdown:
    runs-on: macOS-latest

    env:
      GOOGLESHEETS4_PASSWORD: ${{ secrets.GOOGLESHEETS4_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master

      - name: Install macOS system dependencies
        run: brew install libsodium

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("remotes")' \
                  -e 'remotes::install_deps(dependencies = TRUE)' \
                  -e 'remotes::install_cran("tidyverse")' \
                  -e 'remotes::install_github("tidyverse/tidytemplate")' \
                  -e 'remotes::install_github("hadley/emo")' \
                  -e 'remotes::install_github("jimhester/pkgdown@github-actions-deploy")'

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: |
          pkgdown:::deploy_local(new_process = FALSE, remote_url = 'https://x-access-token:${{secrets.DEPLOY_PAT}}@github.com/${{github.repository}}.git')
        shell: Rscript {0}
