# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: test-coverage

jobs:
  test-coverage:
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v6

      - uses: r-lib/actions/setup-r@v2
        with:
          #r-version: "devel"
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::covr
          needs: coverage

      - name: Test coverage
        run: |
          options(crayon.enabled = TRUE)
          cov <- covr::package_coverage()
          pct <- covr::percent_coverage(cov)
          cat(sprintf("\nCode coverage: %.2f%%\n", pct))
          covr::codecov(coverage = cov, quiet = FALSE)
          if (pct < 100) {
            stop(sprintf("Code coverage is %.2f%%, which is below the required 100%%", pct))
          }
        shell: Rscript {0}
