# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install phate"
  - ps: Bootstrap

# Adapt as necessary starting from here

environment:
  global:
    R_ARCH: x64
    USE_RTOOLS: true
    BIOC_USE_DEVEL: "FALSE"
    _R_CHECK_FORCE_SUGGESTS_: false
    PYTHON: "C:\\Python36-x64"
    RETICULATE_PYTHON: "C:\\Python36-x64"
    CRAN: "https://cloud.r-project.org"
    R_LIBCURL_SSL_REVOKE_BEST_EFFORT: "TRUE"
    CURL_SSL_BACKEND: "openssl"

build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh r_binary_install curl
  - travis-tool.sh bioc_install GenomeInfoDbData
  - travis-tool.sh bioc_install DESeq2
  - travis-tool.sh bioc_install MAST
  - travis-tool.sh bioc_install S4Vectors
  - travis-tool.sh bioc_install SummarizedExperiment
  - travis-tool.sh bioc_install SingleCellExperiment

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
