# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
        Set-TimeZone "GMT Standard Time"

install:
  ps: Bootstrap

# Adapt as necessary starting from here

platform: x64

branches:
  only:
    - main

environment:
  global:
    R_ARCH: x64
    WARNINGS_ARE_ERRORS: 1
    NOT_CRAN: true
    INSTALL_WINUTILS: true
    R_VERSION: release
    USE_RTOOLS: true
    TEMP: "C:\\Users\\appveyor"
    TZ: "UTC"

  matrix:
  - SPARK_VERSION: "1.6.3"
  - SPARK_VERSION: "2.3.1"
  - SPARK_VERSION: "2.4.0"

build_script:
  - travis-tool.sh install_deps

test_script:
  - Rscript -e "install.packages(\".\", repo = NULL, type = \"source\")" && Rscript ci/.ci.R --testthat

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
