# Based on: https://github.com/samapriya/Earth-Engine-Datasets-List/blob/master/.github/workflows/gee_catalog.yml
# Author: Roy Samapriya
name: gee_catalog_lightweight
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip          
          pip install earthengine-api
      - name: dataset upgrade
        run: |
          python3 ./.github/ee_up.py
      - name: file_check
        run: ls -l -a
      - name: commit files
        continue-on-error: true
        run: |
          today=$(date +"%Y-%m-%d %H:%M:%S")
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "updated earthengine version ${today}" -a
      - name: push changes
        continue-on-error: true
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master