language: r
r: devel
sudo: FALSE
compiler: clang

cache:
  apt: true
  packages: true
  ccache: true

warnings_are_errors: TRUE

r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes'
  
addons:
  apt:
    packages:
      - libudunits2-dev
      - libv8-dev
      - libgsl-dev
      - libgdal-dev
      - libproj-dev
  
after_success:
  - travis_wait 30 Rscript -e 'covr::codecov()'
