# .travis.yml
#
# https://docs.travis-ci.com/user/languages/r/

language: r
sudo: false
warnings_are_errors: false
cache: packages


matrix:
  include:
  - r: devel
  - r: release

r_packages: 
  - covr
  - data.table
  - ggplot2
  - rARPACK
  - xgboost

env:
  global:
  - MAKEFLAGS="-j 2"

r_binary_packages: 
  - NMF
  - RANN
  - fastICA
  - RcppRoll
  - Matrix
  - ipred
  - recipes


before_install:
  - cd pkg/caret
 
after_success:
  - Rscript -e 'covr::codecov()'
