language: R
sudo: false
cache: packages
repos:
  CRAN: https://cloud.r-project.org

branches:
  except:
  - gh-pages

warnings_are_errors: true

addons:
  apt:
    packages:
      - libudunits2-dev
      - libzmq3-dev

r_packages:
  - benchmarkme
  - clustermq
  - covr
  - downloader
  - forcats
  - ggplot2
  - lintr
  - readxl

before_script:
  - R -q -e 'install.packages("remotes")'
  - R -q -e 'remotes::install_github("ropensci/rotemplate")'
  - R -q -e 'install.packages("webshot")'
  - R -q -e 'webshot::install_phantomjs()'

script:
  - |
    R CMD build .
    R CMD INSTALL drake*tar.gz
    travis_wait 20 R CMD check drake*tar.gz --no-tests
    travis_wait 20 R -q -e 'cov <- covr::package_coverage(clean = FALSE)' -e 'print(cov)' -e 'covr::codecov(coverage = cov)'

after_success:
  - Rscript -e 'lintr::lint_package()'

after_failure:
  - find *Rcheck -name '*fail' -print -exec cat '{}' \;

env:
  - NOT_CRAN = true
