language: R
cache: packages
sudo: true

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false

addons:
  apt:
    update: true
    packages:
      - libfreetype6
      - libmagick++-dev
      - cargo
      - libavfilter-dev
    sources:
      - sourceline: 'ppa:cran/ffmpeg-4'
      - sourceline: 'ppa:cran/ffmpeg-3'

r_github_packages: r-lib/pkgdown

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - Rscript -e 'update.packages(ask = FALSE)'

matrix:
  include:
  - r: devel
  - r: release
    r_packages:
      - gapminder
    after_success:
    - Rscript -e 'covr::codecov()'

    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(verbose = TRUE, lazy = FALSE, run_dont_run = FALSE)'
      skip_cleanup: true
  - r: oldrel
