language: r

matrix:
  include:
  - r: oldrel
    # Don't use vdiffr on old R release
    env: VDIFFR_RUN_TESTS=false
  - r: release
  - r: devel

warnings_are_errors: true
sudo: required
cache: packages
latex: false

env:
 global:
   - CRAN: http://cran.rstudio.com
   # Use vdiffr by default
   - VDIFFR_RUN_TESTS: true

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
  - devtools

r_github_packages:
  - r-lib/callr
  - r-lib/pkgbuild
  - hadley/pkgdown
  - tidymodels/infer

before_deploy:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  - provider: pages
    skip-cleanup: true
    keep-history: true
    local-dir: docs
    github_token: $GITHUBTRAVIS
    target-branch: gh-pages
    on:
      branch: master
  - provider: pages
    skip-cleanup: true
    keep-history: true
    local-dir: docs
    github_token: $GITHUBTRAVIS
    target-branch: gh-pages-dev
    on:
      branch: develop    


after_success:
  - Rscript -e 'covr::codecov()'


