language: R
sudo: false
cache: packages

notifications:
    email: false

env:
  - NOT_CRAN=true R_LANGSVR_POOL_SIZE=1 R_LANGSVR_TEST_FAST=NO

after_success:
  - travis_wait 30 Rscript -e 'covr::codecov()'
