# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
cache: packages
dist: trusty

env:
  - _R_CHECK_FORCE_SUGGESTS_=false

addons:
  apt:
    packages:
      - libapparmor-dev   
      - libprotobuf-dev
      - protobuf-compiler
      - libicu-dev
