# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

r:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 4.0

addons:
  apt:
    packages:
      - python2.7
      - python-numpy
      - python-scipy
      - python-virtualenv
      - python3-venv
