language: r
cache: packages
jobs:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
    - os: linux
      dist: trusty
      env: R_CODECOV=true
    - os: osx
r_packages:
- covr
after_success:
- R -q -e 'library("covr");codecov()'
