# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  packages: true

warnings_are_errors: true

r_github_packages:
  - gagolews/stringi@v1.4.2

matrix:
  include:
    - name: "Spark 1.6.3 (R 3.2, openjdk7)"
      r: 3.2
      env:
        - SPARK_VERSION="1.6.3"
        - JAVA_VERSION=openjdk7
    - name: "Spark 2.2.1 (R oldrel, oraclejdk8)"
      r: oldrel
      env:
        - SPARK_VERSION="2.2.1"
        - JAVA_VERSION=oraclejdk8
    - name: "Spark 2.3.2 (R release, oraclejdk8)"
      r: release
      env:
        - SPARK_VERSION="2.3.2"
        - JAVA_VERSION=oraclejdk8
    - name: "Spark 2.4.4 (R release, oraclejdk8)"
      r: release
      r_packages:
        - glmnet
      env:
        - SPARK_VERSION="2.4.4"
        - JAVA_VERSION=oraclejdk8
        - CODE_COVERAGE="true"
    - name: "Spark master (R release, oraclejdk8)"
      r: release
      env:
        - SPARK_VERSION="master"
        - JAVA_VERSION=oraclejdk8
    - name: "Spark master (R release, openjdk11)"
      r: release
      env:
        - SPARK_VERSION="master"
        - JAVA_URL="https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.1%2B13/OpenJDK11U-jdk_x64_linux_hotspot_11.0.1_13.tar.gz"
    - name: "Livy 0.5.0 (R release, oraclejdk8, Spark 2.3.0)"
      r: release
      env:
        - LIVY_VERSION="0.5.0"
        - SPARK_VERSION="2.3.0"
        - JAVA_VERSION=oraclejdk8
    - name: "Arrow 0.11.0 (ref = 'dc5df8f')"
      r: release
      env:
        - ARROW_ENABLED="true"
        - ARROW_BRANCH="dc5df8f"
        - JAVA_VERSION=oraclejdk8
      addons:
        apt:
          sources:
            - sourceline: deb https://arrowlib.rstudio.com/ubuntu/ trusty universe
              key_url: https://arrowlib.rstudio.com/ubuntu/red-data-tools-keyring.gpg
          packages:
            - apt-transport-https
            - lsb-release
            - libarrow-dev
            - libarrow-glib-dev
    - name: "Arrow 0.13.0 (ref = 'apache-arrow-0.13.0')"
      r: release
      sudo: true
      env:
        - ARROW_ENABLED="true"
        - ARROW_VERSION="0.13.0"
        - ARROW_BRANCH="apache-arrow-0.13.0"
        - ARROW_SOURCE="install"
        - JAVA_VERSION=oraclejdk8
    - name: "Arrow Devel (ref = '')"
      r: release
      dist: xenial
      sudo: true
      env:
        - ARROW_ENABLED="true"
        - ARROW_VERSION="devel"
        - ARROW_SOURCE="build"
        - JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/jre"
        - LD_LIBRARY_PATH="/usr/local/lib"
      addons:
        apt:
          packages:
            - openjdk-8-jre
    - name: "Deps Devel (tidyverse, r-lib, forge)"
      env: R_DEVEL_PACKAGES="true"
      r_github_packages:
        - tidyverse/dplyr
        - tidyverse/dbplyr
        - tidyverse/tibble
        - r-lib/rlang
        - rstudio/forge
        - r-lib/ellipsis
        - r-dbi/DBI
  allow_failures:
    - env: R_DEVEL_PACKAGES="true"
    - r: release
      dist: xenial
      sudo: true
      env:
        - ARROW_ENABLED="true"
        - ARROW_VERSION="devel"
        - ARROW_SOURCE="build"
        - JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/jre"
        - LD_LIBRARY_PATH="/usr/local/lib"
      addons:
        apt:
          packages:
            - openjdk-8-jre
    - r: release
      env:
        - LIVY_VERSION="0.5.0"
        - SPARK_VERSION="2.3.0"
        - JAVA_VERSION=oraclejdk8

before_install:
  - if [[ ! -z "$JAVA_VERSION" ]]; then jdk_switcher use $JAVA_VERSION;  fi
  - |
    if [[ ! -z "$JAVA_URL" ]]; then
      wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
      source install-jdk.sh --url $JAVA_URL
    fi
  - echo $JAVA_HOME
  - if [[ ! -z "$ARROW_VERSION" ]]; then chmod +x ./ci/arrow-$ARROW_SOURCE.sh ; "./ci/arrow-$ARROW_SOURCE.sh" $ARROW_VERSION; fi
  - if [[ $SPARK_VERSION == "master" ]]; then chmod +x ./ci/spark-master-install.sh ; "./ci/spark-master-install.sh"; fi
  - if [[ $ARROW_ENABLED == "true" ]]; then Rscript ci/.travis.R --arrow $ARROW_BRANCH; fi

script:
  - |
    R CMD build .
    export SPARKLYR_LOG_FILE=/tmp/sparklyr.log
    R CMD check --no-build-vignettes --no-manual --no-tests sparklyr*tar.gz

    if [[ $CODE_COVERAGE == "true" ]]; then
      Rscript ci/.travis.R --coverage
    else
      Rscript ci/.travis.R --testthat
    fi

after_failure:
  - |
    grep -B 10 -A 20 ERROR /tmp/sparklyr.log
