# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

matrix:
  include:
  - name: Strict Latin-1 locale
    r: release
    before_script:
      - sudo locale-gen en_US
      - export LC_ALL=en_US
  - name: Dev rlang and vctrs
    r: release
    r_github_packages:
      - r-lib/rlang
      - r-lib/vctrs
