language: R
cache: packages
sudo: false
warnings_are_errors: true

addons:
  apt:
    packages:
      - libgsl0-dev # for topicmodels
      - libxml2-dev # for XML, a dependency of quanteda

r_packages:
  - covr
  - topicmodels
  - data.table # so data.table tests will get checked

matrix:
  include:
  - r: release
    after_success:
    - Rscript -e 'covr::codecov(coverage = covr::package_coverage(line_exclusions = list("R/compat_lazyeval.R")))'
  - r: oldrel
