# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    # * is a special character in YAML so we have to quote this string
    # 3am Pacific = 11am UTC
    # https://crontab.guru is your friend
    - cron:  '0 11 * * *'
  workflow_dispatch:

name: R-CMD-check-against-dev-vroom

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, tidyverse/vroom
          needs: check

      - uses: r-lib/actions/check-r-package@v2
