on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:
    inputs:
      release:
        description: 'OpenBSD release'
        required: true
        type: choice
        options:
        - '7.6'
        - '7.5'
        - '7.4'
        default: '7.6'

name: openbsd.yaml

jobs:
  openbsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-hub/actions/setup-r-openbsd@main
        with:
          release: ${{ github.event.inputs.release || '7.6' }}

      - name: Test R in OpenBSD VM
        run: |
          getRversion()
          R.version[["platform"]]
          .libPaths()
          .Library
          find.package("pak")
          Sys.getenv()
        shell: Rscript {0}

      - uses: r-hub/actions/debug-shell@v1

      - name: Install system packages
        run: |
          pkg_add -I libbind
          cd /usr/local/lib && ln -s libbind/libbind.so* .
        shell: openbsd {0}

      - name: Install system dependencies
        run: |
          pkg_add -I pandoc
        shell: openbsd {0}

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          pak-version: none
          install-pandoc: false
          install-quarto: false
          cache-version: openbsd-1
          extra-packages: any::rcmdcheck, r-lib/ps
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
          upload-results: never
          upload-snapshots: false
        env:
          NOT_CRAN: true

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: 'check-results'
          path: check
