name: Advice

on:
  pull_request_target:
    types:
      - opened

permissions:
  contents: read

jobs:
  notify:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      pull-requests: write # advice.js comments on PRs
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require(
              `${process.env.GITHUB_WORKSPACE}/.github/workflows/advice.js`
            );
            script({ context, github });
