name: JS

on:
  push:
    paths:
      - mlflow/server/js/**
      - .github/workflows/js.yml
    branches:
      - master
      - branch-[0-9]+.[0-9]+
  pull_request:
    paths:
      - mlflow/server/js/**
      - .github/workflows/js.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  js:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            shell: bash
          - os: windows-latest
            shell: pwsh
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
        working-directory: mlflow/server/js
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Disable problem matcher
        if: runner.os == 'Windows'
        run: |
          echo "::remove-matcher owner=eslint-compact::"
          echo "::remove-matcher owner=eslint-stylish::"
      - name: Install dependencies
        run: |
          yarn install
          git diff --exit-code
      - name: Run lint
        run: |
          yarn run lint
      - name: Run extract-i18n lint
        run: |
          yarn run extract-i18n:base --lint
      - name: Run tests
        run: |
          yarn run test
      - name: Run build
        if: runner.os == 'Linux'
        env:
          # Prevent warnings (emitted from react-pdf) from being treated as errors
          # https://github.com/wojtekmaj/react-pdf/issues/280
          CI: false
        run: |
          yarn run build
