name: MLflow tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      env:
        INSTALL_LARGE_PYTHON_DEPS: true
        INSTALL_SMALL_PYTHON_DEPS: true
      run: |
        source ./travis/install-common-deps.sh
        pip install -r ./travis/lint-requirements.txt
    - name: Run tests
      run: |
        export PATH="$HOME/miniconda/bin:$PATH"
        source activate test-environment
        ./lint.sh

  python-small:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      env:
        INSTALL_LARGE_PYTHON_DEPS: true
      run: |
        source ./travis/install-common-deps.sh
    - name: Run tests
      run: |
        export PATH="$HOME/miniconda/bin:$PATH"
        source activate test-environment
        ./travis/run-small-python-tests.sh

  java:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Install dependencies
      run: |
        source ./travis/install-common-deps.sh
    - name: Run tests
      run: |
        export PATH="$HOME/miniconda/bin:$PATH"
        source activate test-environment
        cd mlflow/java
        mvn clean package -q

  js:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mlflow/server/js
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install dependencies
      run: |
        npm i
    - name: Run lint
      run: |
        npm run lint
    - name: Run tests
      run: |
        npm run test

  protos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        wget https://github.com/google/protobuf/releases/download/v3.6.0/protoc-3.6.0-linux-x86_64.zip -O $HOME/protoc.zip
        sudo unzip $HOME/protoc.zip -d /usr
    - name: Run tests
      run: |
        ./test-generate-protos.sh
