name: Preview docs

on:
  pull_request_target:

jobs:
  main:
    if: github.repository == 'mlflow/mlflow' && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install requests
      - name: Create preview link
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python dev/preview_docs.py \
            --commit-sha ${{ github.event.pull_request.head.sha }} \
            --pull-number ${{ github.event.pull_request.number }} \
            --workflow-run-id ${{ github.run_id }}
