# A workflow to validate at least one release-note category is selected

name: Release-note category

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Validate
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // https://github.com/actions/github-script#run-a-separate-file
            const script = require(
              `${process.env.GITHUB_WORKSPACE}/.github/workflows/release-note-category.js`
            );
            script({ core, context, github });
